Data download script (for task purpose)
ArmaForces/MissionFramework pull request #9
Opened 2024-02-17 18:21 UTC by 3Mydlo3

Based on:
https://github.com/Theseus-Aegis/Mods/pull/609

**When merged this pull request will:**
- Add data download script
  - Start the download via ACE action.
  - Display progress on laptop screen
  - Completes (fires `successful` event) when player unplugs the device (ACE action) after download reaches 100%
  - Public events for custom integrations:
    - `afmf_task_download_start` (server side only)
    - `afmf_task_download_started`
    - `afmf_task_download_successful`
    - `afmf_task_download_failed`

Requires ACE, skips loading if not loaded.

2024-02-18 13:12 UTC, veteran29 requested changes
Feeling like this is quite more complicated than it needs to be.

ACE actions should basically be always added and show or not depending on their conditions, no much need to dynamically add/remove them, they do not cost much performance.

Also the download handling feels bit meh, I would just make it based on time instead of ticks as it basically allows every client to handle everything locally if they know start time (and that's all you need to broadcast then). I think the random time per tick does not brinch much value. If you want some randomness you can have some minor random coefficient for total download time that's not known.

2024-02-18 13:12 UTC, veteran29 commented on addons/task_download/XEH_postInit.sqf
> +};
Event handlers should be added in PreInit if they're supposed to be working for JIP.

2024-02-18 13:12 UTC, veteran29 commented on addons/task_download/config.cpp
> +            "ace_interact_menu"
We do not want hard dependency on ACE in this addon. Only CBA allowed, add `skipWhenMissingDependencies = 1;` or handle in script.

2024-02-18 13:12 UTC, veteran29 commented on addons/task_download/functions/fnc_setup.sqf
> + * Public: No
```suggestion
 * Public: Yes
```

2024-02-18 13:12 UTC, veteran29 commented on addons/task_download/stringtable.xml
> +            <Polish>Zadane pobierania</Polish>
```suggestion
            <Polish>Zadanie pobierania</Polish>
```

2024-02-18 13:12 UTC, veteran29 commented on addons/task_download/functions/fnc_started.sqf
> +[_object, ACTION_TYPE, _actionPath] call ACEFUNC(interact_menu,removeActionFromObject);
I do not see much need for this as the condition should handle the action showing or not.

2024-02-18 13:12 UTC, veteran29 commented on addons/task_download/functions/fnc_initCheckProgressAction.sqf
> + * Initializes download action on given object.
```suggestion
 * Initializes check progress action on given object.
```

2024-02-19 21:10 UTC, 3Mydlo3 commented on addons/task_download/XEH_postInit.sqf
> +};
Removed that one.

2024-02-19 21:16 UTC, 3Mydlo3 commented
> Feeling like this is quite more complicated than it needs to be.

I've simplified it heavily. It's now mostly clientside, except for download start & end. I've also cleaned up setup.

2024-02-19 23:44 UTC, veteran29 requested changes

2024-02-19 23:44 UTC, veteran29 commented on addons/task_download/functions/fnc_canContinue.sqf
> +true
Setting default value in params instead of doing `isNil` is IMO more idiomatic for SQF, null objects are not alive, so this can be greatly simplified:
```suggestion
params [["_object", objNull]];

alive _object // return
```

2024-02-19 23:44 UTC, veteran29 commented on addons/task_download/functions/fnc_formatEstimatedTimeRemaining.sqf
> + * Function checks if download from given object can continue.
```suggestion
 * Formats remaining estimated time as a formatted string.
```

2024-02-19 23:44 UTC, veteran29 commented on addons/task_download/functions/fnc_formatEstimatedTimeRemaining.sqf
> + * True if download can continue <STRING>
```suggestion
 * Formatted time <STRING>
```

2024-02-19 23:44 UTC, veteran29 commented on addons/task_download/functions/fnc_formatEstimatedTimeRemaining.sqf
> + * [laptop] call afmf_task_download_fnc_canContinue
```suggestion
 * [60, 50] call afmf_task_download_fnc_formatEstimatedTimeRemaining
```

2024-02-19 23:44 UTC, veteran29 commented on addons/task_download/functions/fnc_setupSimple.sqf
> + * [laptop] call afmf_task_download_fnc_setupSimple
```suggestion
 * [laptop, 66, 2096] call afmf_task_download_fnc_setupSimple
```

2024-02-19 23:46 UTC, veteran29 approved these changes
LGTM

2024-02-20 17:14 UTC, merged